import { createClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";
import { jsPDF } from "jspdf";
import fs from "fs";
import path from "path";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ paymentId: string }> }
) {
  const { paymentId } = await params;
  const supabase = await createClient();
  const { data: userData } = await supabase.auth.getUser();
  if (!userData.user) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  // 取付款记录 + 关联客户
  const { data: payment } = await supabase
    .from("payments")
    .select("*, clients:client_id(name, email)")
    .eq("id", paymentId)
    .eq("user_id", userData.user.id)
    .single();

  if (!payment) {
    return NextResponse.json({ error: "Payment not found" }, { status: 404 });
  }

  // 取摄影师信息
  const { data: profile } = await supabase
    .from("profiles")
    .select("studio_name, full_name")
    .eq("id", userData.user.id)
    .single();

  const studioName = profile?.studio_name || "Photography Studio";
  const photographerName = profile?.full_name || userData.user.email || "";
  const clientName = (payment.clients as any)?.name || "Client";
  const clientEmail = (payment.clients as any)?.email || "";

  // 生成 PDF
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  // Logo — 加载本地文件
  const logoPath = path.join(process.cwd(), "public", "logo-96.png");
  if (fs.existsSync(logoPath)) {
    const logoData = fs.readFileSync(logoPath).toString("base64");
    doc.addImage(`data:image/png;base64,${logoData}`, "PNG", 15, 12, 12, 12);
  }

  // 标题
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(212, 160, 69);
  doc.text("INVOICE", 15, 35);

  // Studio info
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.setFont("helvetica", "normal");
  doc.text(studioName, 15, 45);
  doc.text(photographerName, 15, 50);

  // 分隔线
  doc.setDrawColor(212, 160, 69);
  doc.setLineWidth(0.5);
  doc.line(15, 58, 195, 58);

  // 发票详情
  doc.setFontSize(10);
  doc.setTextColor(40, 40, 40);
  const leftX = 15;
  const rightX = 120;
  let y = 68;

  doc.setFont("helvetica", "bold");
  doc.text("Invoice #", leftX, y);
  doc.text("Date", leftX, y + 8);
  doc.text("Client", leftX, y + 16);
  doc.text("Description", leftX, y + 24);
  doc.text("Amount", leftX, y + 32);

  doc.setFont("helvetica", "normal");
  const invoiceNum = payment.id.slice(0, 8).toUpperCase();
  const paidDate = payment.paid_at ? new Date(payment.paid_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }) : "—";
  doc.text(invoiceNum, rightX, y);
  doc.text(paidDate, rightX, y + 8);
  doc.text(clientName, rightX, y + 16);
  if (clientEmail) doc.text(clientEmail, rightX, y + 20);
  doc.text(payment.description || "Photography services", rightX, y + 24);
  doc.text(`$${((payment.amount || 0) / 100).toLocaleString()} USD`, rightX, y + 32);

  // 底部
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Thank you for your business!", 105, 270, { align: "center" });
  doc.text(`Generated by Lightmeter — ${new Date().toISOString().split("T")[0]}`, 105, 276, { align: "center" });

  const pdfBuffer = Buffer.from(doc.output("arraybuffer"));
  return new NextResponse(pdfBuffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="invoice-${invoiceNum}.pdf"`,
    },
  });
}
